// Temas de demostración usados cuando el backend no está conectado.
export const topics = [
  {
    id: 1,
    code: 'INF-26-014',
    title: 'Detección temprana de incendios mediante visión computacional',
    summary: 'Diseño de un sistema que analice imágenes en tiempo real para anticipar focos de incendio en zonas de interfaz urbano-forestal.',
    description: 'El proyecto propone construir y evaluar un prototipo de visión computacional capaz de identificar columnas de humo y patrones térmicos en imágenes capturadas desde puntos de observación. El trabajo combinará preparación de datos, evaluación de modelos y una interfaz de monitoreo orientada a la toma de decisiones.',
    area: 'Inteligencia Artificial',
    professor: 'Dra. Camila Arancibia',
    professorEmail: 'camila.arancibia@usach.cl',
    professorDepartment: 'Departamento de Ingeniería Informática',
    totalSlots: 2,
    reservedSlots: 0,
    modality: 'Individual o grupal',
    dedication: '12 horas semanales',
    location: 'Laboratorio de Computación Visual',
    technologies: ['Python', 'PyTorch', 'OpenCV', 'Vue'],
    objectives: [
      'Construir un conjunto de datos representativo para el contexto nacional.',
      'Comparar arquitecturas de detección y segmentación bajo restricciones de tiempo real.',
      'Diseñar un panel de monitoreo que comunique alertas con claridad.',
    ],
    requirements: [
      'Programación intermedia en Python.',
      'Interés por aprendizaje automático y procesamiento de imágenes.',
      'Disponibilidad para reuniones semanales de seguimiento.',
    ],
    featured: true,
    publishedAt: '12 AGO 2026',
  },
  {
    id: 2,
    code: 'INF-26-009',
    title: 'Accesibilidad digital para servicios universitarios',
    summary: 'Auditoría y rediseño de trámites digitales críticos utilizando WCAG y pruebas participativas con estudiantes.',
    description: 'La propuesta busca identificar barreras de acceso en servicios universitarios y desarrollar patrones de interfaz verificables, reutilizables y alineados con estándares internacionales de accesibilidad.',
    area: 'Interacción Humano-Computador',
    professor: 'Mg. Sebastián Mella',
    professorEmail: 'sebastian.mella@usach.cl',
    professorDepartment: 'Departamento de Ingeniería Informática',
    totalSlots: 2,
    reservedSlots: 1,
    modality: 'Grupal',
    dedication: '10 horas semanales',
    location: 'Laboratorio de Experiencia de Usuario',
    technologies: ['Vue', 'Playwright', 'Figma', 'ARIA'],
    objectives: [
      'Caracterizar barreras en una muestra de trámites universitarios.',
      'Diseñar y validar componentes accesibles reutilizables.',
      'Documentar recomendaciones técnicas y organizacionales.',
    ],
    requirements: ['Conocimientos de desarrollo web.', 'Interés por diseño centrado en las personas.'],
    featured: false,
    publishedAt: '09 AGO 2026',
  },
  {
    id: 3,
    code: 'INF-26-021',
    title: 'Optimización de recorridos para logística de última milla',
    summary: 'Modelos heurísticos para mejorar la planificación de entregas urbanas considerando ventanas horarias y carga vehicular.',
    description: 'Se estudiarán estrategias de optimización combinatoria aplicadas a una red urbana dinámica, construyendo un simulador que permita comparar resultados y visualizar rutas.',
    area: 'Ciencia de Datos',
    professor: 'Dr. Rodrigo Álvarez',
    professorEmail: 'rodrigo.alvarez@usach.cl',
    professorDepartment: 'Departamento de Ingeniería Informática',
    totalSlots: 1,
    reservedSlots: 0,
    modality: 'Individual',
    dedication: '12 horas semanales',
    location: 'Laboratorio de Sistemas Inteligentes',
    technologies: ['Python', 'PostgreSQL', 'OR-Tools', 'MapLibre'],
    objectives: ['Formalizar las restricciones del problema.', 'Comparar heurísticas en escenarios simulados.', 'Construir una herramienta visual de análisis.'],
    requirements: ['Investigación de operaciones básica.', 'Programación en Python o lenguaje equivalente.'],
    featured: false,
    publishedAt: '08 AGO 2026',
  },
  {
    id: 4,
    code: 'INF-26-018',
    title: 'Seguridad y trazabilidad en cadenas de suministro alimentarias',
    summary: 'Arquitectura distribuida para registrar eventos críticos y verificar el origen de productos agroalimentarios.',
    description: 'El trabajo contempla el diseño de una arquitectura de eventos que mantenga trazabilidad verificable desde el productor hasta el consumidor.',
    area: 'Sistemas Distribuidos',
    professor: 'Dra. Valentina Soto',
    professorEmail: 'valentina.soto@usach.cl',
    professorDepartment: 'Departamento de Ingeniería Informática',
    totalSlots: 2,
    reservedSlots: 0,
    modality: 'Individual o grupal',
    dedication: '10 horas semanales',
    location: 'Laboratorio de Sistemas Distribuidos',
    technologies: ['Java', 'Spring Boot', 'PostgreSQL', 'Kafka'],
    objectives: ['Definir eventos y actores de la cadena.', 'Implementar un prototipo auditable.', 'Evaluar rendimiento y consistencia.'],
    requirements: ['Programación orientada a objetos.', 'Fundamentos de bases de datos.'],
    featured: false,
    publishedAt: '05 AGO 2026',
  },
  {
    id: 5,
    code: 'INF-26-003',
    title: 'Analítica de aprendizaje para cursos de primer año',
    summary: 'Indicadores explicables para detectar tempranamente dificultades académicas y orientar acciones de acompañamiento.',
    description: 'La tesis explorará datos históricos anonimizados para proponer indicadores tempranos, priorizando explicabilidad, privacidad y uso responsable.',
    area: 'Ciencia de Datos',
    professor: 'Mg. Paula Contreras',
    professorEmail: 'paula.contreras@usach.cl',
    professorDepartment: 'Departamento de Ingeniería Informática',
    totalSlots: 2,
    reservedSlots: 1,
    modality: 'Grupal',
    dedication: '10 horas semanales',
    location: 'Modalidad híbrida',
    technologies: ['Python', 'Pandas', 'PostgreSQL', 'Metabase'],
    objectives: ['Definir indicadores accionables.', 'Evaluar modelos explicables.', 'Prototipar un tablero para equipos docentes.'],
    requirements: ['Estadística básica.', 'Manejo responsable de información sensible.'],
    featured: false,
    publishedAt: '02 AGO 2026',
  },
]

export const areas = [...new Set(topics.map((topic) => topic.area))].sort()
export const professors = [...new Set(topics.map((topic) => topic.professor))].sort()

export function getTopicById(id) {
  return topics.find((topic) => topic.id === Number(id))
}
